# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkdataform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLineEdit, QTableView, QHeaderView, QVBoxLayout
from PyQt5.QtCore import Qt, QSortFilterProxyModel
from PyQt5.QtGui import QStandardItemModel, QStandardItem
excel_dir=r'D:\home task\3rd semester\Mid term Project\CS261F21PID46\CS261F21PID46scrapingplaystore.csv'
class Ui_MainWindow2(object):
        def loaddata(self,path):
                df= pd.read_csv(path)
                if df.size ==0:
                        return
                df.fillna('',inplace=True)
                self.tableWidget.setRowCount(df.shape[0])
                self.tableWidget.setColumnCount(df.shape[1])
                self.tableWidget.setHorizontalHeaderLabels(df.columns)
                print(df)
                for row in df.iterrows():
                        values = row[1]
                        for col_index,value in enumerate(values):

                                tableitem=QtWidgets.QTableWidgetItem(str(value))
                                self.tableWidget.setItem(row[0],col_index,tableitem)

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1000, 600)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.frame = QtWidgets.QFrame(self.centralwidget)
                self.frame.setGeometry(QtCore.QRect(0, 0, 821, 211))
                self.frame.setStyleSheet("*{\n"
"\n"
"    font-family:Times News Roman;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color:grey;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background:#FFF;\n"
"    border-radius:20px;\n"
"    background-color:grey;\n"
"    \n"
"}\n"
"\n"
"QToolButton{\n"
"    background:#FFF;\n"
"    border-radius:30px\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    color:#333;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background:transparent;\n"
"    color:rgb(171, 171, 171);\n"
"    border:none;\n"
"    border-bottom: 1px solid rgb(171, 171, 171);\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:green;\n"
"\n"
"}\n"
"")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.lineEdit = QtWidgets.QLineEdit(self.frame)
                self.lineEdit.setGeometry(QtCore.QRect(590, 10, 113, 20))
                self.lineEdit.setObjectName("lineEdit")
                self.label = QtWidgets.QLabel(self.frame)
                self.label.setGeometry(QtCore.QRect(520, 10, 47, 13))
                self.label.setObjectName("label")
                self.frame_3 = QtWidgets.QFrame(self.frame)
                self.frame_3.setGeometry(QtCore.QRect(520, 50, 271, 161))
                self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_3.setObjectName("frame_3")
                self.comboBox = QtWidgets.QComboBox(self.frame_3)
                self.comboBox.setGeometry(QtCore.QRect(148, 0, 101, 22))
                self.comboBox.setObjectName("comboBox")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.comboBox_2 = QtWidgets.QComboBox(self.frame_3)
                self.comboBox_2.setGeometry(QtCore.QRect(150, 80, 101, 22))
                self.comboBox_2.setObjectName("comboBox_2")
                self.comboBox_2.addItem("")
                self.comboBox_2.addItem("")
                self.comboBox_2.addItem("")
                self.comboBox_3 = QtWidgets.QComboBox(self.frame_3)
                self.comboBox_3.setGeometry(QtCore.QRect(150, 40, 101, 22))
                self.comboBox_3.setObjectName("comboBox_3")
                self.comboBox_3.addItem("")
                self.comboBox_3.addItem("")
                self.label_2 = QtWidgets.QLabel(self.frame_3)
                self.label_2.setGeometry(QtCore.QRect(20, 40, 81, 21))
                self.label_2.setObjectName("label_2")
                self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
                self.pushButton_2.setGeometry(QtCore.QRect(90, 130, 75, 23))
                self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    color : #FFF;\n"
"    background-color: rgb(27, 27, 27);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:red;\n"
"\n"
"}")
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_3 = QtWidgets.QPushButton(self.frame)
                self.pushButton_3.setGeometry(QtCore.QRect(710, 10, 75, 23))
                self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    color : #FFF;\n"
"    background-color: rgb(27, 27, 27);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:red;\n"
"\n"
"}")
                self.pushButton_3.setObjectName("pushButton_3")
                self.pushButton = QtWidgets.QPushButton(self.frame)
                self.pushButton.setGeometry(QtCore.QRect(10, 160, 111, 41))
                self.pushButton.setObjectName("pushButton")
                self.pushButton.clicked.connect(lambda _,xl_path=excel_dir :self.loaddata(xl_path))
                self.frame_2 = QtWidgets.QFrame(self.centralwidget)
                self.frame_2.setGeometry(QtCore.QRect(0, 200, 791, 401))
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
                self.tableWidget.setGeometry(QtCore.QRect(0, 10, 801, 391))
                self.tableWidget.setObjectName("tableWidget")
                self.tableWidget.setColumnCount(0)
                self.tableWidget.setRowCount(0)
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label.setText(_translate("MainWindow", "Search"))
                self.comboBox.setItemText(0, _translate("MainWindow", "Size"))
                self.comboBox.setItemText(1, _translate("MainWindow", "Name"))
                self.comboBox.setItemText(2, _translate("MainWindow", "Rating"))
                self.comboBox_2.setItemText(0, _translate("MainWindow", "Name"))
                self.comboBox_2.setItemText(1, _translate("MainWindow", "Size"))
                self.comboBox_2.setItemText(2, _translate("MainWindow", "Rating"))
                self.comboBox_3.setItemText(0, _translate("MainWindow", "And"))
                self.comboBox_3.setItemText(1, _translate("MainWindow", "or"))
                self.label_2.setText(_translate("MainWindow", "Search with"))
                self.pushButton_2.setText(_translate("MainWindow", "Search"))
                self.pushButton_3.setText(_translate("MainWindow", "Search"))
                self.pushButton.setText(_translate("MainWindow", "Load"))
               # search()
                
def CheckData ():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    excel_dir='CS261F21PID46scrapingplaystore.csv'
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
#CheckData()
def search ():
        mainLayout = Ui_MainWindow2()
        for row, i in enumerate(excel_dir):
            item = int(excel_dir(i))
            excel_dir.setItem(row, 0, item)
        model = QStandardItemModel(len(excel_dir), 1)
        filter_proxy_model = QSortFilterProxyModel()
        filter_proxy_model.setSourceModel(model)
        filter_proxy_model.setFilterCaseSensitivity(Qt.CaseInsensitive)
        filter_proxy_model.setFilterKeyColumn(0)
        search_field = QLineEdit()          
        search_field.setStyleSheet('font-size: 35px; height: 60px;')
        search_field.textChanged.connect(filter_proxy_model.setFilterRegExp)
        mainLayout.addWidget(search_field)
        table = QTableView()
        table.setModel(filter_proxy_model)
        mainLayout.addWidget(table)

        Ui_MainWindow2.setLayout(mainLayout)

        
        
